### ISSUE TITLE
Bug in attention mask loss term?

### ISSUE THREAD

**Issue by ikb-a** [stelzner/monet#1]
I think there's a bug in the loss, the ground-truth mask is created by:

https://github.com/stelzner/monet/blob/4bce6ff1137e5bea974daa38422495c6c53eeb44/model.py#L175

Which would be NxWxHxSlots. However, the corresponding mask reconstruction is created by:

https://github.com/stelzner/monet/blob/4bce6ff1137e5bea974daa38422495c6c53eeb44/model.py#L177

Which would be NxHxWxSlots. As a result, I believe the loss term is between computed between the reconstructed mask and the transpose of the original mask.

**Comment by stelzner** [comment]
Good catch! This should fix it: https://github.com/stelzner/monet/commit/f4cbd968cde8a9cbe2994e2fc05debaa0d0bdbb9
